<?php
// $Id: personell_check.module,v 1.1 2011/02/01 20:27:20 ashipunova Exp ashipunova $
/*
 * Form to check new person data against old ones
 * ?q=personell_check
*/

function personell_check_menu() {
  
  $items = array();
  $items['personell_check'] = array (
    'title' => t('Check new person data against old ones'),
//    'page callback' => 'personell_check_page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('personell_check_form'),
    'access arguments' => array('administer nodes'),
    'type' => MENU_CALLBACK,
    'file' => 'personell_check.inc',
    );

  $items['two_person'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => 'two_person_page');

  return $items;
}

function two_person_page() {
  $checked_nids  = variable_get('person_checked', '');
  if(!empty($checked_nids)) {
    foreach ($checked_nids as $checked_nid) {
      $header       = array('Title', 'Nid');
      $rows['data'] = array();
        dpr($checked_nid);
        $node       = node_load($checked_nid);
        $node_nid   = $node->nid;
        $node_title = $node->title;
        $node_type  = $node->type;
        $node_link  = l($nid, 'node/'.$nid);
    }
  }
}


/*
 function display_report_page()
{
  $csv2drupal_submit_time = variable_get(csv2drupal_submit_time, time());
  $sql = "SELECT nid FROM {node} WHERE created >= %d ORDER BY nid DESC";
  $db_result = db_query($sql, $csv2drupal_submit_time);

  $header       = array('Title', 'Nid');
  $rows['data'] = array();
  while ($res   = db_fetch_object($db_result)) {
    $nid        = $res->nid;
    $node       = node_load($nid);
    $node_nid   = $node->nid;
    $node_title = $node->title;
    $node_type  = $node->type;
    $node_link  = l($nid, 'node/'.$nid);
    if ($node_type != $old_node_type) {
      $rows[] = array(array('data' => 'Type = ' . $node_type, 'colspan' => 2, 'font size' => 4, 'align' => 'center'));
      $old_node_type = $node_type;
    }
    $rows[] = array('Title = ' . $node_title, $node_link);
  }
  if (count($rows) == 1)
      $rows[] = array("No nodes was saved");

  variable_del(csv2drupal_submit_time);
  return theme_table($header, $rows);
}

 */

//function personell_check_page() {
//  return drupal_get_form('personell_check_form');
//}

