<?php
// $Id: personell_check.module, v 1.0 2011-01-28 ashipunova $
/*
 * Form to check new person data against old ones
 * ?q=personell_check
*/

function personell_check_menu() {
  
  $items = array();
  $items['personell_check'] = array (
    'title' => t('Check new person data against old ones'),
    'page callback' => drupal_get_form,
    'access arguments' => array('administer nodes'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'personell_check_form.inc',
    );
  return $items;
}

